# Generated by Django 6.0.7 on 2026-08-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_delete_etudiant_delete_note_delete_professeur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classe',
            old_name='nom',
            new_name='classe',
        ),
        migrations.RenameField(
            model_name='matiere',
            old_name='nom',
            new_name='matière',
        ),
    ]
