# Generated by Django 6.0.7 on 2026-08-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_rename_nom_classe_classe_rename_nom_matiere_matière'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matiere',
            old_name='matière',
            new_name='matiere',
        ),
    ]
