# Generated by Django 6.0.7 on 2026-08-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_rename_matière_matiere_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='coefficient',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
