# Generated by Django 6.0.7 on 2026-07-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='justification',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
