# Generated by Django 6.0.7 on 2026-08-18 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0003_note_date'),
        ('school', '0004_rename_matière_matiere_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.matiere'),
        ),
    ]
