# Generated by Django 6.0.7 on 2026-08-20 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0004_absence_matiere'),
        ('profil', '0010_alter_etudiant_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='professeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.professeur'),
        ),
    ]
