# Generated by Django 6.0.7 on 2026-07-21 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_etudiant_professeur'),
        ('school', '0002_delete_etudiant_delete_note_delete_professeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classe'),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professeurs', to='school.classe'),
        ),
    ]
