# Generated by Django 6.0.7 on 2026-07-28 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_alter_etudiant_classe_alter_professeur_matiere'),
        ('school', '0002_delete_etudiant_delete_note_delete_professeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professeurs', to='school.matiere'),
        ),
    ]
