# Generated by Django 6.0.7 on 2026-07-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_alter_professeur_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='user_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='user_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
