# Generated by Django 6.0.7 on 2026-07-28 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_alter_etudiant_user_name_alter_professeur_user_name'),
        ('school', '0002_delete_etudiant_delete_note_delete_professeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classe'),
        ),
    ]
