# Generated by Django 6.0.7 on 2026-08-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0007_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
