# Generated by Django 6.0.7 on 2026-08-31 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0010_alter_etudiant_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
